// flow-typed signature: 651cdf75eb6212f37fcfa12c8fe6413c
// flow-typed version: <<STUB>>/serverless-aws-alias_v^1.5.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-aws-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-aws-alias' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless-aws-alias/lib/aliasRestructureStack' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/collectUserResources' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/configureAliasStack' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/createAliasStack' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/listAliases' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/logs' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/removeAlias' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/stackInformation' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/stackops/apiGateway' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/stackops/cwEvents' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/stackops/events' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/stackops/functions' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/stackops/init' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/stackops/lambdaRole' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/stackops/snsEvents' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/stackops/userResources' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/updateAliasStack' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/updateFunctionAlias' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/uploadAliasArtifacts' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/utils' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/lib/validate' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/test/aliasRestructureStack.test' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/test/configureAliasStack.test' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/test/createAliasStack.test' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/test/index.test' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/test/logs.test' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/test/removeAlias.test' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/test/stackops/apiGateway.test' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/test/stackops/init.test' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/test/stackops/lambdaRole.test' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/test/stackops/snsEvents.test' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/test/updateAliasStack.test' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/test/uploadAliasArtifacts.test' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/test/utils.test' {
  declare module.exports: any;
}

declare module 'serverless-aws-alias/test/validate.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless-aws-alias/index' {
  declare module.exports: $Exports<'serverless-aws-alias'>;
}
declare module 'serverless-aws-alias/index.js' {
  declare module.exports: $Exports<'serverless-aws-alias'>;
}
declare module 'serverless-aws-alias/lib/aliasRestructureStack.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/aliasRestructureStack'>;
}
declare module 'serverless-aws-alias/lib/collectUserResources.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/collectUserResources'>;
}
declare module 'serverless-aws-alias/lib/configureAliasStack.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/configureAliasStack'>;
}
declare module 'serverless-aws-alias/lib/createAliasStack.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/createAliasStack'>;
}
declare module 'serverless-aws-alias/lib/listAliases.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/listAliases'>;
}
declare module 'serverless-aws-alias/lib/logs.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/logs'>;
}
declare module 'serverless-aws-alias/lib/removeAlias.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/removeAlias'>;
}
declare module 'serverless-aws-alias/lib/stackInformation.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/stackInformation'>;
}
declare module 'serverless-aws-alias/lib/stackops/apiGateway.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/stackops/apiGateway'>;
}
declare module 'serverless-aws-alias/lib/stackops/cwEvents.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/stackops/cwEvents'>;
}
declare module 'serverless-aws-alias/lib/stackops/events.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/stackops/events'>;
}
declare module 'serverless-aws-alias/lib/stackops/functions.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/stackops/functions'>;
}
declare module 'serverless-aws-alias/lib/stackops/init.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/stackops/init'>;
}
declare module 'serverless-aws-alias/lib/stackops/lambdaRole.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/stackops/lambdaRole'>;
}
declare module 'serverless-aws-alias/lib/stackops/snsEvents.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/stackops/snsEvents'>;
}
declare module 'serverless-aws-alias/lib/stackops/userResources.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/stackops/userResources'>;
}
declare module 'serverless-aws-alias/lib/updateAliasStack.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/updateAliasStack'>;
}
declare module 'serverless-aws-alias/lib/updateFunctionAlias.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/updateFunctionAlias'>;
}
declare module 'serverless-aws-alias/lib/uploadAliasArtifacts.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/uploadAliasArtifacts'>;
}
declare module 'serverless-aws-alias/lib/utils.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/utils'>;
}
declare module 'serverless-aws-alias/lib/validate.js' {
  declare module.exports: $Exports<'serverless-aws-alias/lib/validate'>;
}
declare module 'serverless-aws-alias/test/aliasRestructureStack.test.js' {
  declare module.exports: $Exports<'serverless-aws-alias/test/aliasRestructureStack.test'>;
}
declare module 'serverless-aws-alias/test/configureAliasStack.test.js' {
  declare module.exports: $Exports<'serverless-aws-alias/test/configureAliasStack.test'>;
}
declare module 'serverless-aws-alias/test/createAliasStack.test.js' {
  declare module.exports: $Exports<'serverless-aws-alias/test/createAliasStack.test'>;
}
declare module 'serverless-aws-alias/test/index.test.js' {
  declare module.exports: $Exports<'serverless-aws-alias/test/index.test'>;
}
declare module 'serverless-aws-alias/test/logs.test.js' {
  declare module.exports: $Exports<'serverless-aws-alias/test/logs.test'>;
}
declare module 'serverless-aws-alias/test/removeAlias.test.js' {
  declare module.exports: $Exports<'serverless-aws-alias/test/removeAlias.test'>;
}
declare module 'serverless-aws-alias/test/stackops/apiGateway.test.js' {
  declare module.exports: $Exports<'serverless-aws-alias/test/stackops/apiGateway.test'>;
}
declare module 'serverless-aws-alias/test/stackops/init.test.js' {
  declare module.exports: $Exports<'serverless-aws-alias/test/stackops/init.test'>;
}
declare module 'serverless-aws-alias/test/stackops/lambdaRole.test.js' {
  declare module.exports: $Exports<'serverless-aws-alias/test/stackops/lambdaRole.test'>;
}
declare module 'serverless-aws-alias/test/stackops/snsEvents.test.js' {
  declare module.exports: $Exports<'serverless-aws-alias/test/stackops/snsEvents.test'>;
}
declare module 'serverless-aws-alias/test/updateAliasStack.test.js' {
  declare module.exports: $Exports<'serverless-aws-alias/test/updateAliasStack.test'>;
}
declare module 'serverless-aws-alias/test/uploadAliasArtifacts.test.js' {
  declare module.exports: $Exports<'serverless-aws-alias/test/uploadAliasArtifacts.test'>;
}
declare module 'serverless-aws-alias/test/utils.test.js' {
  declare module.exports: $Exports<'serverless-aws-alias/test/utils.test'>;
}
declare module 'serverless-aws-alias/test/validate.test.js' {
  declare module.exports: $Exports<'serverless-aws-alias/test/validate.test'>;
}
